import { useMemo, useState } from "react";
import { HiArrowLeft, HiArrowRight, HiBolt, HiBuildingOffice2, HiCheckBadge, HiClock, HiLink, HiMapPin, HiPhone, HiPlus, HiShieldCheck, HiUserGroup, HiWrenchScrewdriver } from "react-icons/hi2";
import { useNavigate } from "react-router-dom";
import EcoLayout from "@/pages/Ecosystem/EcoLayout";
import useEscapeKey from "@/hooks/useEscapeKey";
import { usePropertiesData } from "../../data/PropertiesDataContext";
import "./service-network.css";

const responders=[
  {id:"rsp-1",name:"Ana Castillo",kind:"internal",specialty:"Coordinación operativa",skills:["Inspecciones","Entregas","Accesos"],zone:"CDMX",availability:"Disponible",active:2,rating:"Equipo OwnTerra",phone:"55 2055 1802",color:"green"},
  {id:"rsp-2",name:"Diego Ruiz",kind:"internal",specialty:"Mantenimiento interno",skills:["Electricidad","Inventarios","Supervisión"],zone:"CDMX · Edo. Méx.",availability:"En servicio",active:3,rating:"Equipo OwnTerra",phone:"55 8190 4431",color:"amber"},
  {id:"rsp-3",name:"Plomería Díaz",kind:"external",specialty:"Plomería residencial",skills:["Fugas","Bombas","Calentadores"],zone:"CDMX centro y poniente",availability:"En servicio",active:1,rating:"4.9 · 28 servicios",phone:"55 6432 7781",color:"amber"},
  {id:"rsp-4",name:"Obra Ligera MTY",kind:"external",specialty:"Adecuaciones comerciales",skills:["Plafón","Pintura","Albañilería"],zone:"Monterrey metropolitano",availability:"Disponible mañana",active:1,rating:"4.7 · 16 servicios",phone:"81 2098 7740",color:"blue"},
  {id:"rsp-5",name:"Climas del Centro",kind:"external",specialty:"Aire acondicionado",skills:["Minisplit","Preventivo","Diagnóstico"],zone:"CDMX",availability:"Disponible",active:1,rating:"4.8 · 21 servicios",phone:"55 3221 9084",color:"green"},
  {id:"rsp-6",name:"Caseta Jacarandas",kind:"external",specialty:"Seguridad y accesos",skills:["Accesos","Bitácora","Paquetería"],zone:"Torre Jacarandas",availability:"Turno activo",active:1,rating:"Sitio permanente",phone:"55 4108 0021",color:"green"},
  {id:"rsp-7",name:"Construcciones Tapalpa",kind:"external",specialty:"Cubiertas y madera",skills:["Techos","Humedad","Carpintería"],zone:"Tapalpa y alrededores",availability:"Cotizando",active:1,rating:"4.6 · 9 servicios",phone:"33 2210 6577",color:"blue"},
];

const workOrders=[
  {ticket:"OT-240381",title:"Fuga debajo del lavabo",assignee:"Plomería Díaz",status:"En sitio",sla:"Respuesta en 14 min",tone:"urgent"},
  {ticket:"OT-240349",title:"Plafón con humedad",assignee:"Obra Ligera MTY",status:"En progreso",sla:"Actualizado hace 2 h",tone:"active"},
  {ticket:"OT-240301",title:"Verificar minisplit",assignee:"Climas del Centro",status:"Por confirmar",sla:"Respuesta límite 16:30",tone:"waiting"},
  {ticket:"OT-240366",title:"Revisión de cubierta",assignee:"Construcciones Tapalpa",status:"Cotizando",sla:"Visita mañana 09:00",tone:"waiting"},
];

function ServiceNetworkPage(){
  const navigate=useNavigate();
  const {tickets}=usePropertiesData();
  const [filter,setFilter]=useState("all");
  const [selected,setSelected]=useState(responders[2]);
  const [showInvite,setShowInvite]=useState(false);
  const [accountType,setAccountType]=useState("independent");
  useEscapeKey(()=>setShowInvite(false),showInvite);
  const visible=useMemo(()=>filter==="all"?responders:responders.filter(item=>item.kind===filter),[filter]);
  return <EcoLayout active="properties" title="OwnTerra Properties" subtitle="Operación · Red de servicio"><main className="service-page">
    <header className="service-heading"><button type="button" onClick={()=>navigate("/properties")}><HiArrowLeft/> Properties</button><div><span>Quién resuelve</span><h1>Red de servicio. <em className="service-soon">Próximamente</em></h1><p>Personas, especialidades y carga operativa antes de asignar el trabajo.</p></div><button type="button" onClick={()=>setShowInvite(true)}><HiPlus/> Invitar proveedor</button></header>
    <section className="service-access-model"><div><HiUserGroup/><span><strong>Equipo interno</strong><small>Reutiliza usuarios, roles y Mi Día del ecosistema.</small></span></div><i/><div><HiLink/><span><strong>Proveedor externo</strong><small>Usa su Portal de servicio con acceso limitado por asignación.</small></span></div><button type="button" onClick={()=>navigate("/portal-servicio")}>Ver experiencia del técnico <HiArrowRight/></button></section>
    <section className="service-enrollment"><div><HiLink/><span><small>Registro autónomo</small><strong>Comparte tu enlace para que los proveedores soliciten acceso.</strong><em>ownterra.com/servicio/registro/OT-DEMO</em></span></div><button type="button" onClick={()=>navigate("/servicio/registro")}>Ver formulario público</button><i/><div><span className="service-request-count">3</span><span><small>Solicitudes pendientes</small><strong>Revisa identidad, especialidad y cobertura antes de aprobar.</strong></span></div><button type="button" disabled title="Todavía no está conectado — vista previa del diseño">Revisar solicitudes</button></section>
    <section className="service-stats"><article><small>Red aprobada</small><strong>{responders.length}</strong><span>2 internos · 5 externos</span></article><article><small>Solicitudes nuevas</small><strong>3</strong><span>Pendientes de revisión</span></article><article><small>Trabajos abiertos</small><strong>{tickets.filter(item=>item.status!=="resolved").length}</strong><span>En toda la operación</span></article><article><small>Sin responsable</small><strong>{tickets.filter(item=>item.status!=="resolved"&&!item.assignee).length}</strong><span>Requieren asignación</span></article></section>
    <section className="service-layout"><div className="service-directory"><header><div><span>Directorio operativo</span><h2>Responsables</h2></div><nav><button type="button" className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Todos</button><button type="button" className={filter==="internal"?"active":""} onClick={()=>setFilter("internal")}>Equipo</button><button type="button" className={filter==="external"?"active":""} onClick={()=>setFilter("external")}>Externos</button></nav></header><div>{visible.map(item=><button type="button" className={selected.id===item.id?"active":""} onClick={()=>setSelected(item)} key={item.id}><span className="service-avatar">{item.name.split(" ").slice(0,2).map(word=>word[0]).join("")}</span><span><small>{item.kind==="internal"?"Equipo interno":"Proveedor externo"}</small><strong>{item.name}</strong><em>{item.specialty}</em></span><i className={item.color}>{item.availability}</i></button>)}</div></div>
      <article className="service-profile"><header><span className="service-profile-avatar">{selected.name.split(" ").slice(0,2).map(word=>word[0]).join("")}</span><div><small>{selected.kind==="internal"?"Integrante del ecosistema":"Colaborador externo"}</small><h2>{selected.name}</h2><p>{selected.specialty}</p></div><span className={`service-availability ${selected.color}`}><HiCheckBadge/> {selected.availability}</span></header><section className="service-profile-facts"><div><HiMapPin/><span><small>Cobertura</small><strong>{selected.zone}</strong></span></div><div><HiWrenchScrewdriver/><span><small>Carga actual</small><strong>{selected.active} {selected.active===1?"trabajo":"trabajos"}</strong></span></div><div><HiShieldCheck/><span><small>Referencia</small><strong>{selected.rating}</strong></span></div><div><HiPhone/><span><small>Contacto</small><strong>{selected.phone}</strong></span></div></section><section className="service-skills"><small>Puede resolver</small><div>{selected.skills.map(skill=><span key={skill}>{skill}</span>)}</div></section><section className="service-profile-access"><div><HiLink/><span><strong>{selected.kind==="internal"?"Acceso desde OwnTerra":"Orden de trabajo por enlace"}</strong><small>{selected.kind==="internal"?"Ve tickets asignados dentro de Mi Día.":"Puede aceptar, actualizar, reportar y chatear sin ver el resto del sistema."}</small></span></div><button type="button" onClick={()=>navigate(selected.kind==="internal"?"/ecosistema/mi-dia":"/portal-servicio")}>Vista del responsable</button></section></article>
    </section>
    <section className="dispatch-board"><header><div><span>Despacho actual</span><h2>Órdenes en movimiento</h2></div><p>Asignar no termina el flujo: cada responsable debe aceptar y mantener visible el siguiente paso.</p></header><div>{workOrders.map(order=><article key={order.ticket}><span className={`dispatch-icon ${order.tone}`}>{order.tone==="urgent"?<HiBolt/>:<HiClock/>}</span><div><small>{order.ticket}</small><strong>{order.title}</strong></div><div><small>Responsable</small><strong>{order.assignee}</strong></div><i className={order.tone}>{order.status}</i><span>{order.sla}</span><HiArrowRight/></article>)}</div></section>
    {showInvite?<div className="service-invite-backdrop" onClick={()=>setShowInvite(false)}><section className="service-invite" role="dialog" aria-modal="true" aria-label="Agregar proveedor" onClick={event=>event.stopPropagation()}><header><div><span>Red de servicio</span><h2>Invitar proveedor</h2><p>Crea la identidad externa y envía un acceso protegido.</p></div><button type="button" onClick={()=>setShowInvite(false)}>×</button></header><div className="service-invite-types"><button type="button" className={accountType==="independent"?"active":""} onClick={()=>setAccountType("independent")}><HiUserGroup/><span><strong>Profesional independiente</strong><small>Una persona recibe y resuelve sus órdenes.</small></span></button><button type="button" className={accountType==="company"?"active":""} onClick={()=>setAccountType("company")}><HiBuildingOffice2/><span><strong>Empresa proveedora</strong><small>Un coordinador puede asignar trabajos a técnicos.</small></span></button></div><form><label><span>{accountType==="company"?"Razón social":"Nombre completo"}</span><input placeholder={accountType==="company"?"Ej. Climas del Centro, S.A.":"Ej. Rafael Díaz"}/></label>{accountType==="company"?<label><span>Contacto administrador</span><input placeholder="Nombre del coordinador"/></label>:null}<label><span>Correo de invitación</span><input type="email" placeholder="contacto@proveedor.mx"/></label><label><span>Teléfono / WhatsApp</span><input placeholder="+52 55 0000 0000"/></label><label><span>Especialidad principal</span><select><option>Plomería</option><option>Electricidad</option><option>Aire acondicionado</option><option>Seguridad</option><option>Limpieza</option><option>Construcción y acabados</option></select></label><label><span>Tipo de acceso</span><select><option>Portal de servicio permanente</option><option>Invitado por una sola orden</option></select></label></form><aside><HiLink/><div><strong>Se enviará una invitación de un solo uso</strong><span>Vence en 48 horas. El proveedor validará su correo o teléfono antes de crear el acceso.</span></div><button type="button" onClick={()=>navigate("/servicio/invitacion")}>Vista previa</button></aside><footer><button type="button" onClick={()=>setShowInvite(false)}>Cancelar</button><button type="button" disabled title="Todavía no está conectado — vista previa del diseño">Crear y enviar invitación</button></footer></section></div>:null}
  </main></EcoLayout>;
}
export default ServiceNetworkPage;
