import { useMemo, useState } from "react";
import { HiArrowLeft, HiMagnifyingGlass, HiPlus } from "react-icons/hi2";
import { Navigate, useNavigate, useParams } from "react-router-dom";
import EcoLayout from "@/pages/Ecosystem/EcoLayout";
import "./module-preview.css";

const moduleData = {
  contratos:{title:"Contratos",group:"Operación",statement:"Vigencias y acuerdos alrededor del mismo inmueble.",action:"Nuevo contrato",metric:"3 por vencer",columns:["Contrato","Vinculado a","Responsable","Estado"],rows:[["CTR-024","Torre Jacarandas · 302","Mariana Torres","Vigente"],["CTR-019","Casa Olivo","Jorge Álvarez","Por vencer"],["CTR-011","Plaza Norte · Local 4","Café Alba, S.A.","Vigente"]]},
  rentas:{title:"Rentas",group:"Operación",statement:"Cobranza clara, sin separar cargos de personas.",action:"Registrar pago",metric:"93% cobrado",columns:["Movimiento","Vinculado a","Importe","Estado"],rows:[["REN-1082","Torre Jacarandas · 302","$18,500","Pagado"],["REN-1081","Casa Olivo","$24,000","Pendiente"],["REN-1074","Plaza Norte · Local 4","$3,200","Vencido"]]},
  mantenimiento:{title:"Mantenimiento",group:"Operación",statement:"Incidencias atendidas con todo su contexto.",action:"Nueva solicitud",metric:"8 abiertos",columns:["Solicitud","Vinculado a","Responsable","Estado"],rows:[["Fuga en lavabo","Torre Jacarandas · 302","Plomería Díaz","En progreso"],["Luminaria de pasillo","Plaza Norte","Equipo interno","Abierto"],["Revisión de minisplit","Casa Olivo","Climas del Sur","Resuelto"]]},
  documentos:{title:"Documentos",group:"Portafolio",statement:"Un expediente vivo para cada relación.",action:"Subir documento",metric:"148 archivos",columns:["Documento","Vinculado a","Actualizado","Estado"],rows:[["Contrato firmado 302.pdf","CTR-024","12 ago 2026","Vigente"],["Escritura Casa Olivo.pdf","Casa Olivo","04 ago 2026","Verificado"],["Recibo mantenimiento.pdf","REN-1074","01 ago 2026","Nuevo"]]},
  inspecciones:{title:"Inspecciones",group:"Operación",statement:"Evidencia y seguimiento en una sola historia.",action:"Programar",metric:"5 programadas",columns:["Inspección","Vinculado a","Responsable","Estado"],rows:[["Entrada","Torre Jacarandas · 302","Ana Castillo","Programada"],["Periódica","Casa Olivo","Diego Ruiz","Completada"],["Mantenimiento","Plaza Norte · Local 4","Ana Castillo","Con hallazgos"]]},
  prospectos:{title:"Prospectos",group:"Comercial",statement:"Personas interesadas, no filas en un embudo.",action:"Nuevo prospecto",metric:"18% conversión",columns:["Persona","Interés","Responsable","Estado"],rows:[["Andrea Molina","Torre Jacarandas · 401","Luis Rojas","Visita agendada"],["Grupo Velar","Plaza Norte · Local 2","Ana Castillo","Negociación"],["Carlos Mejía","Casa Olivo","Luis Rojas","Nuevo"]]},
  proveedores:{title:"Proveedores",group:"Operación",statement:"Servicios confiables cerca de cada incidencia.",action:"Nuevo proveedor",metric:"24 activos",columns:["Proveedor","Especialidad","Evaluación","Estado"],rows:[["Plomería Díaz","Plomería","4.9 / 5","Disponible"],["Climas del Sur","Aire acondicionado","4.7 / 5","Asignado"],["Segurix","Seguridad","4.5 / 5","Disponible"]]},
  publicaciones:{title:"Publicaciones",group:"Comercial",statement:"Del activo privado a una historia que convierte.",action:"Nueva publicación",metric:"12 activas",columns:["Publicación","Modalidad","Interés","Estado"],rows:[["Departamento en Del Valle","Renta","21 consultas","Publicada"],["Local comercial con terraza","Renta comercial","8 consultas","En revisión"],["Casa Olivo · 3 recámaras","Venta","34 consultas","Pausada"]]},
  mensajes:{title:"Mensajes",group:"Relaciones",statement:"Conversaciones con el inmueble siempre presente.",action:"Nuevo mensaje",metric:"6 sin leer",columns:["Conversación","Vinculado a","Responsable","Estado"],rows:[["Mariana Torres","Contrato CTR-024","Ana Castillo","Sin leer"],["Plomería Díaz","Ticket MAN-041","Diego Ruiz","Respondido"],["Andrea Molina","Prospecto","Luis Rojas","Pendiente"]]},
  notificaciones:{title:"Atención",group:"Relaciones",statement:"Solo aquello que necesita una decisión humana.",action:"Configurar",metric:"9 pendientes",columns:["Atención requerida","Vinculado a","Responsable","Estado"],rows:[["Contrato próximo a vencer","CTR-019","Ana Castillo","Pendiente"],["Renta vencida","REN-1074","Café Alba, S.A.","Enviada"],["Nueva consulta","Casa Olivo","Luis Rojas","Leída"]]},
  actividad:{title:"Actividad",group:"Operación",statement:"Una línea de tiempo para todo el portafolio.",action:"Exportar",metric:"17 hoy",columns:["Evento","Vinculado a","Realizado por","Resultado"],rows:[["Pago registrado","REN-1082","Ana Castillo","Completado"],["Estatus actualizado","MAN-041","Diego Ruiz","En progreso"],["Documento cargado","CTR-024","Ana Castillo","Completado"]]},
  "portal-inquilino":{title:"Experiencia del inquilino",group:"Relaciones",statement:"Lo necesario para vivir y resolver, nada más.",action:"Vista previa",metric:"38 activos",columns:["Inquilino","Hogar","Próximo paso","Acceso"],rows:[["Mariana Torres","Torre Jacarandas · 302","Pago · 05 sep","Activo"],["Jorge Álvarez","Casa Olivo","Completar perfil","Invitado"],["Café Alba, S.A.","Plaza Norte · Local 4","Revisar solicitud","Activo"]]},
  "portal-propietario":{title:"Experiencia del propietario",group:"Relaciones",statement:"Rendimiento y tranquilidad en una sola mirada.",action:"Vista previa",metric:"14 activos",columns:["Propietario","Portafolio","Rendimiento","Acceso"],rows:[["Inversiones Roble","18 unidades","89% ocupación","Activo"],["Sofía Mendoza","1 unidad","100% ocupación","Activo"],["Grupo Arboleda","7 unidades","71% ocupación","Invitado"]]},
};

function ModulePreviewPage(){
  const {moduleKey}=useParams(); const navigate=useNavigate(); const [query,setQuery]=useState(""); const data=moduleData[moduleKey];
  const rows=useMemo(()=>data?.rows.filter(row=>row.join(" ").toLowerCase().includes(query.toLowerCase()))||[],[data,query]);
  if(!data)return <Navigate to="/properties" replace/>;
  return <EcoLayout active="properties" title="OwnTerra Properties" subtitle={`${data.group} · Mismo contexto`}><main className="unicell-page">
    <header className="unicell-heading"><button type="button" className="unicell-back" onClick={()=>navigate("/properties")}><HiArrowLeft/> Properties</button><div><span>{data.group}</span><h1>{data.title} <em className="unicell-soon">Próximamente</em></h1><p>{data.statement}</p></div><button type="button" className="unicell-action" disabled title="Todavía no está conectado — vista previa del diseño"><HiPlus/>{data.action}</button></header>
    <section className="unicell-context"><div><small>Contexto activo</small><strong>Todo el portafolio</strong></div><i/><div><small>Pulso</small><strong>{data.metric}</strong></div><p>Vista previa de diseño con datos de ejemplo. Aún no está conectada a información real.</p></section>
    <section className="unicell-surface"><label className="unicell-search"><HiMagnifyingGlass/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Buscar en ${data.title.toLowerCase()}`}/></label><div className="unicell-table"><div className="unicell-row unicell-row--head">{data.columns.map(column=><span key={column}>{column}</span>)}<span/></div>{rows.map(row=><div className="unicell-row" key={row.join("-")}>{row.map((cell,index)=><span key={`${cell}-${index}`} className={index===row.length-1?"unicell-state":""}>{cell}</span>)}</div>)}</div>{!rows.length?<p className="unicell-empty">No encontramos coincidencias.</p>:null}</section>
  </main></EcoLayout>;
}
export default ModulePreviewPage;
