import { useEffect, useMemo, useState } from "react";
import { HiArrowLeft, HiChatBubbleLeftRight, HiCheckCircle, HiClock, HiExclamationTriangle, HiPaperAirplane, HiPlus, HiTicket, HiWrenchScrewdriver, HiXMark } from "react-icons/hi2";
import { useNavigate, useSearchParams } from "react-router-dom";
import EcoLayout from "@/pages/Ecosystem/EcoLayout";
import useEscapeKey from "@/hooks/useEscapeKey";
import { usePropertiesData } from "../../data/PropertiesDataContext";
import { TICKET_PRIORITY_LABEL, TICKET_STATUS_LABEL, TICKET_TYPE_LABEL } from "./ticketModel";
import "./tickets.css";

const emptyDraft = { title:"", description:"", propertyId:"", unitId:"", type:"maintenance", priority:"medium", assignee:"" };
const statusOrder = ["open", "in_progress", "waiting", "resolved"];
const ticketStories={
  "tk-1":{events:[{time:"18 ago 2026 · 09:20",title:"Solicitud recibida",text:"El residente reportó goteo constante en el baño principal.",state:"done"},{time:"18 ago 2026 · 09:34",title:"Proveedor asignado",text:"Plomería Díaz confirmó atención para esta tarde.",state:"done"},{time:"18 ago 2026 · 14:08",title:"Trabajo iniciado",text:"El técnico ingresó a la unidad y cerró la llave de paso.",state:"current"},{time:"Pendiente · sin fecha",title:"Validación y cierre",text:"Falta confirmar reparación con el residente.",state:"next"}],incident:{title:"Se requiere una pieza adicional",text:"La válvula instalada no es compatible. El proveedor está cotizando reemplazo y estima 90 minutos adicionales.",time:"18 ago 2026 · 14:26"},messages:[{from:"Plomería Díaz",role:"Proveedor",time:"18 ago · 14:09",text:"Ya estamos dentro de la unidad. La fuga viene de la válvula angular."},{from:"Fernando",role:"Administración",time:"18 ago · 14:12",text:"Gracias. ¿Se puede resolver hoy sin cortar agua al edificio?"},{from:"Plomería Díaz",role:"Proveedor",time:"18 ago · 14:26",text:"Sí, pero necesitamos una válvula distinta. Ya la estamos buscando; calculamos 90 minutos más."}]},
  "tk-4":{events:[{time:"16 ago 2026 · 09:40",title:"Hallazgo registrado",text:"Se detectó humedad durante la adecuación del local.",state:"done"},{time:"16 ago 2026 · 12:15",title:"Inspección realizada",text:"Obra Ligera MTY revisó plafón e instalaciones.",state:"done"},{time:"18 ago 2026 · 10:20",title:"En reparación",text:"Se trabaja sobre el sello de la bajante.",state:"current"},{time:"Pendiente · sin fecha",title:"Secado y cierre",text:"Se verificará humedad antes de cerrar el plafón.",state:"next"}],incident:{title:"El origen no estaba en el local",text:"La filtración proviene de una bajante común; se amplió el alcance a la administración de la plaza.",time:"16 ago 2026 · 12:42"},messages:[{from:"Obra Ligera MTY",role:"Proveedor",time:"18 ago · 10:20",text:"Abrimos el plafón y encontramos la bajante afectada."},{from:"Diego",role:"Operación",time:"18 ago · 10:31",text:"Documenten con fotos antes de cerrar, por favor."}]}
};
const defaultStory={events:[{time:"Fecha y hora de registro",title:"Ticket creado",text:"La solicitud quedó vinculada con su inmueble y responsable.",state:"done"},{time:"Última actualización",title:"En seguimiento",text:"El equipo trabaja en la siguiente acción del ticket.",state:"current"},{time:"Pendiente · sin fecha",title:"Confirmación de cierre",text:"La persona solicitante validará el resultado.",state:"next"}],incident:null,messages:[{from:"OwnTerra",role:"Sistema",time:"Ahora",text:"La conversación está lista para coordinar esta solicitud."}]};
const dateStamp=value=>value?new Intl.DateTimeFormat("es-MX",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value)).replace(",", " ·"):"Sin registro";

function TicketsPage(){
  const navigate=useNavigate();
  const [searchParams,setSearchParams]=useSearchParams();
  const {properties,units,tickets,addTicket,changeTicketStatus}=usePropertiesData();
  const [draft,setDraft]=useState(emptyDraft);
  const [creating,setCreating]=useState(false);
  const [statusFilter,setStatusFilter]=useState("active");
  const [selectedTicket,setSelectedTicket]=useState(null);
  const [message,setMessage]=useState("");
  const [extraMessages,setExtraMessages]=useState({});
  useEscapeKey(()=>setCreating(false),creating&&!selectedTicket);
  useEscapeKey(()=>setSelectedTicket(null),Boolean(selectedTicket));
  const propertyById=useMemo(()=>Object.fromEntries(properties.map(item=>[item.id,item])),[properties]);
  const unitById=useMemo(()=>Object.fromEntries(units.map(item=>[item.id,item])),[units]);
  const availableUnits=units.filter(unit=>!draft.propertyId||unit.propertyId===draft.propertyId);
  const visible=tickets.filter(ticket=>statusFilter==="all"||(statusFilter==="active"?ticket.status!=="resolved":ticket.status===statusFilter));
  const openCreate=(unitId="")=>{const unit=unitById[unitId];setDraft({...emptyDraft,unitId:unit?.id||"",propertyId:unit?.propertyId||""});setCreating(true);};
  useEffect(()=>{if(searchParams.get("create")!=="1")return;openCreate(searchParams.get("unitId")||"");setSearchParams({}, {replace:true});},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const save=(event)=>{event.preventDefault();if(!draft.title.trim())return;addTicket(draft);setCreating(false);};
  const sendMessage=(event)=>{event.preventDefault();if(!message.trim()||!selectedTicket)return;setExtraMessages(current=>({...current,[selectedTicket.id]:[...(current[selectedTicket.id]||[]),{from:"Fernando",role:"Administración",time:"Ahora",text:message.trim()}]}));setMessage("");};
  return <EcoLayout active="properties" title="OwnTerra Properties" subtitle="Operación · Tickets"><main className="ticket-page">
    <header className="ticket-heading"><button type="button" onClick={()=>navigate("/properties/condominios/operacion")}><HiArrowLeft/> Operación condominal</button><div><span>Atención operativa</span><h1>Tickets persistentes en la sesión</h1><p>Solicitud, conversación, responsable y cambios de estado permanecen conectados mientras operas Properties.</p></div><button type="button" className="ticket-create" onClick={()=>openCreate()}><HiPlus/> Nuevo ticket</button></header>
    <section className="ticket-summary" aria-label="Resumen de tickets"><div><small>Activos</small><strong>{tickets.filter(ticket=>ticket.status!=="resolved").length}</strong></div>{statusOrder.slice(0,3).map(status=><div key={status}><small>{TICKET_STATUS_LABEL[status]}</small><strong>{tickets.filter(ticket=>ticket.status===status).length}</strong></div>)}</section>
    <section className="ticket-toolbar"><div><button type="button" className={statusFilter==="active"?"active":""} onClick={()=>setStatusFilter("active")}>Activos</button><button type="button" className={statusFilter==="resolved"?"active":""} onClick={()=>setStatusFilter("resolved")}>Resueltos</button><button type="button" className={statusFilter==="all"?"active":""} onClick={()=>setStatusFilter("all")}>Todos</button></div><span>{visible.length} solicitudes</span></section>
    {!tickets.length?<section className="ticket-zero"><span><HiTicket/></span><h2>La operación está al día.</h2><p>Crea un ticket de mantenimiento, limpieza, seguridad o cualquier atención necesaria.</p><button type="button" onClick={()=>openCreate()}><HiPlus/> Crear primer ticket</button></section>:<section className="ticket-list" aria-label="Listado de tickets">{visible.map(ticket=>{const unit=unitById[ticket.unitId];const property=propertyById[ticket.propertyId];return <article key={ticket.id} role="button" tabIndex="0" aria-label={`Abrir seguimiento de ${ticket.title}`} onClick={()=>setSelectedTicket(ticket)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setSelectedTicket(ticket)}}}><div className={`ticket-priority ${ticket.priority}`}/><div className="ticket-main"><span>{ticket.folio} · {TICKET_TYPE_LABEL[ticket.type]}</span><h2>{ticket.title}</h2><p>{ticket.description||"Sin descripción adicional."}</p></div><div className="ticket-link"><small>Vinculado a</small><strong>{unit?.identifier||property?.name||"Operación general"}</strong>{unit&&<span>{property?.name}</span>}</div><div className="ticket-owner"><small>Responsable</small><strong>{ticket.assignee||"Por asignar"}</strong><span>{TICKET_PRIORITY_LABEL[ticket.priority]}</span></div><label onClick={event=>event.stopPropagation()}><span>Estado</span><select aria-label={`Estado de ${ticket.title}`} value={ticket.status} onChange={event=>changeTicketStatus(ticket.id,event.target.value)}>{statusOrder.map(status=><option value={status} key={status}>{TICKET_STATUS_LABEL[status]}</option>)}</select></label></article>})}{!visible.length&&<p className="ticket-no-results">No hay tickets en este estado.</p>}</section>}
    {creating&&<div className="ticket-modal-backdrop" role="presentation"><section className="ticket-modal" role="dialog" aria-modal="true" aria-labelledby="ticket-modal-title"><header><div><span>Nueva solicitud</span><h2 id="ticket-modal-title">Crear ticket</h2><p>Registra qué sucede y dónde requiere atención.</p></div><button type="button" aria-label="Cerrar" onClick={()=>setCreating(false)}><HiXMark/></button></header><form onSubmit={save}><label className="wide"><span>Asunto *</span><input autoFocus required value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})} placeholder="Ej. Fuga en lavabo"/></label><label><span>Tipo</span><select value={draft.type} onChange={event=>setDraft({...draft,type:event.target.value})}>{Object.entries(TICKET_TYPE_LABEL).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label><span>Prioridad</span><select value={draft.priority} onChange={event=>setDraft({...draft,priority:event.target.value})}>{Object.entries(TICKET_PRIORITY_LABEL).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label><span>Propiedad</span><select value={draft.propertyId} onChange={event=>setDraft({...draft,propertyId:event.target.value,unitId:""})}><option value="">Operación general</option>{properties.filter(item=>item.status!=="archived").map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label><span>Unidad</span><select value={draft.unitId} onChange={event=>{const unit=unitById[event.target.value];setDraft({...draft,unitId:event.target.value,propertyId:unit?.propertyId||draft.propertyId})}}><option value="">Toda la propiedad</option>{availableUnits.filter(item=>item.status!=="archived").map(item=><option value={item.id} key={item.id}>{item.identifier}</option>)}</select></label><label className="wide"><span>Responsable</span><input value={draft.assignee} onChange={event=>setDraft({...draft,assignee:event.target.value})} placeholder="Persona, equipo o proveedor"/></label><label className="wide"><span>Descripción</span><textarea rows="4" value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})} placeholder="Describe el problema, acceso y cualquier detalle útil…"/></label><footer><button type="button" onClick={()=>setCreating(false)}>Cancelar</button><button type="submit">Crear ticket</button></footer></form></section></div>}
    {selectedTicket&&(()=>{const story=ticketStories[selectedTicket.id]||defaultStory;const unit=unitById[selectedTicket.unitId];const property=propertyById[selectedTicket.propertyId];const messages=[...story.messages,...(extraMessages[selectedTicket.id]||[])];return <div className="ticket-trace-backdrop" role="presentation" onClick={()=>setSelectedTicket(null)}><section className="ticket-trace" role="dialog" aria-modal="true" aria-label={`Seguimiento de ${selectedTicket.title}`} onClick={event=>event.stopPropagation()}><header><div><span>{selectedTicket.folio} · {TICKET_TYPE_LABEL[selectedTicket.type]}</span><h2>{selectedTicket.title}</h2><p>{property?.name}{unit?` · ${unit.identifier}`:""}</p><div className="ticket-audit-stamps"><time>Creado: {dateStamp(selectedTicket.createdAt)}</time><time>Actualizado: {dateStamp(selectedTicket.updatedAt)}</time></div></div><button type="button" className="ticket-trace-close" aria-label="Cerrar seguimiento" onClick={()=>setSelectedTicket(null)}><HiXMark/><span>Cerrar</span></button></header><div className="ticket-trace-layout"><div className="ticket-trace-story"><section className="trace-status"><header><HiWrenchScrewdriver/><div><small>Estado actual</small><strong>{TICKET_STATUS_LABEL[selectedTicket.status]}</strong></div><span>{selectedTicket.assignee||"Por asignar"}</span></header><div>{story.events.map((event,index)=><article className={event.state} key={`${event.title}-${index}`}><i>{event.state==="done"?<HiCheckCircle/>:<HiClock/>}</i><div><time>{event.time}</time><h3>{event.title}</h3><p>{event.text}</p></div></article>)}</div></section>{story.incident&&<section className="trace-incident"><HiExclamationTriangle/><div><time>Imprevisto · {story.incident.time}</time><h3>{story.incident.title}</h3><p>{story.incident.text}</p></div></section>}</div><section className="trace-chat"><header><HiChatBubbleLeftRight/><div><strong>Conversación del ticket</strong><span>{selectedTicket.assignee||"Equipo responsable"} · Administración</span></div></header><div className="trace-messages">{messages.map((item,index)=><article className={item.from==="Fernando"?"mine":""} key={`${item.time}-${index}`}><div><strong>{item.from}</strong><time>{item.role} · {item.time}</time></div><p>{item.text}</p></article>)}</div><form onSubmit={sendMessage}><textarea rows="2" value={message} onChange={event=>setMessage(event.target.value)} placeholder="Escribe una actualización o pregunta…"/><button type="submit" aria-label="Enviar mensaje"><HiPaperAirplane/></button></form><footer>Todo mensaje conserva el contexto y queda en la bitácora.</footer></section></div></section></div>})()}
  </main></EcoLayout>;
}
export default TicketsPage;
