import {useMemo,useState} from "react";
import {HiArrowRight,HiBanknotes,HiBolt,HiBuildingOffice2,HiCalendarDays,HiChartBar,HiCheckCircle,HiClock,HiDocumentArrowDown,HiExclamationTriangle,HiMegaphone,HiScale,HiTicket,HiUserGroup,HiWrenchScrewdriver} from "react-icons/hi2";
import {useNavigate} from "react-router-dom";
import {usePropertiesData} from "../../data/PropertiesDataContext";
import {demoHospitalityReservations} from "../hospitality/demoHospitalityData";
import {buildCommunityReport,REPORT_PERIOD_LABEL,trend} from "./communityReportModel";
import "./community-reports.css";

const money=value=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(value||0);
const previousBenchmarks={
  day:{collectionRate:24,serviceAmount:9800,activeTickets:5,occupancy:62},
  week:{collectionRate:25,serviceAmount:10800,activeTickets:6,occupancy:65},
  month:{collectionRate:31,serviceAmount:11900,activeTickets:7,occupancy:68},
  year:{collectionRate:72,serviceAmount:121000,activeTickets:9,occupancy:71},
};

function Trend({value,inverse=false}){const good=inverse?value<=0:value>=0;return <span className={`report-trend ${good?"positive":"negative"}`}>{value>0?"+":""}{value}% vs periodo anterior</span>}

function CommunityReportsPanel({community,units,onOpenModule}){
  const navigate=useNavigate();
  const data=usePropertiesData();
  const [period,setPeriod]=useState("month");
  const [detail,setDetail]=useState("executive");
  const property=data.properties.find(item=>item.id===community?.propertyId);
  const charges=data.condoCharges.filter(item=>item.communityId===community?.id);
  const announcements=data.announcements.filter(item=>item.communityId===community?.id);
  const reservations=data.reservations.filter(item=>item.communityId===community?.id);
  const votes=data.votes.filter(item=>item.communityId===community?.id);
  const services=data.utilityServices.filter(item=>item.communityId===community?.id);
  const serviceIds=new Set(services.map(item=>item.id));
  const readings=data.utilityReadings.filter(item=>serviceIds.has(item.serviceId));
  const unitIds=new Set(units.map(item=>item.id));
  const tickets=data.tickets.filter(item=>item.propertyId===community?.propertyId||unitIds.has(item.unitId));
  const relations=data.personUnitRelations.filter(item=>item.communityId===community?.id);
  const people=data.communityPeople.filter(item=>item.communityIds?.includes(community?.id));
  const report=useMemo(()=>buildCommunityReport({community,units,charges,announcements,reservations,votes,services,readings,tickets,people,relations},period),[community,units,charges,announcements,reservations,votes,services,readings,tickets,people,relations,period]);
  const benchmark=previousBenchmarks[period];
  const rentalPotential=units.filter(item=>item.status!=="archived").reduce((sum,item)=>sum+Number(item.suggestedRent||0),0);
  const hospitality=demoHospitalityReservations.filter(item=>unitIds.has(item.unitId));
  const hospitalityRevenue=hospitality.reduce((sum,item)=>sum+item.total,0);
  const hospitalityCollected=hospitality.reduce((sum,item)=>sum+item.paid,0);
  const currentStays=hospitality.filter(item=>item.status==="checked_in").length;
  const serviceByType=services.reduce((acc,item)=>({...acc,[item.type]:(acc[item.type]||0)+Number(item.amount||0)}),{});
  const reportGenerated=`26 ago 2026 · ${REPORT_PERIOD_LABEL[period]}`;

  return <section className="community-report-center">
    <header className="report-center-heading"><div><span>Centro transversal</span><h2>Reporte completo de la comunidad</h2><p>Datos de portafolio, operación, servicios, rentas, cobranza, mantenimiento y participación en una sola lectura.</p></div><div><label>Periodo<select value={period} onChange={event=>setPeriod(event.target.value)}><option value="day">Diario</option><option value="week">Semanal</option><option value="month">Mensual</option><option value="year">Anual</option></select></label><button type="button" onClick={()=>globalThis.print?.()}><HiDocumentArrowDown/> Imprimir / PDF</button></div></header>
    <aside className="report-context"><div><small>Comunidad</small><strong>{community?.name}</strong></div><div><small>Inmueble</small><strong>{property?.name}</strong></div><div><small>Periodo</small><strong>{REPORT_PERIOD_LABEL[period]}</strong></div><div><small>Generado</small><strong>{reportGenerated}</strong></div><span>Datos demo de la sesión</span></aside>
    <nav className="report-section-tabs"><button type="button" className={detail==="executive"?"active":""} onClick={()=>setDetail("executive")}>Resumen</button><button type="button" className={detail==="finance"?"active":""} onClick={()=>setDetail("finance")}>Finanzas y rentas</button><button type="button" className={detail==="utilities"?"active":""} onClick={()=>setDetail("utilities")}>Servicios</button><button type="button" className={detail==="maintenance"?"active":""} onClick={()=>setDetail("maintenance")}>Mantenimiento</button><button type="button" className={detail==="community"?"active":""} onClick={()=>setDetail("community")}>Comunidad</button></nav>

    {detail==="executive"&&<><section className="report-hero-metrics"><article><span><HiBuildingOffice2/> Ocupación</span><strong>{report.units.occupancy}%</strong><p>{report.units.occupied} de {report.units.total} unidades ocupadas</p><Trend value={trend(report.units.occupancy,benchmark.occupancy)}/></article><article><span><HiBanknotes/> Cobranza</span><strong>{report.finance.collectionRate}%</strong><p>{money(report.finance.collected)} de {money(report.finance.billed)}</p><Trend value={trend(report.finance.collectionRate,benchmark.collectionRate)}/></article><article><span><HiBolt/> Servicios</span><strong>{money(report.utilities.amount)}</strong><p>{report.utilities.anomalies} anomalías · {report.utilities.evidencePending} evidencias pendientes</p><Trend value={trend(report.utilities.amount,benchmark.serviceAmount)} inverse/></article><article><span><HiTicket/> Tickets activos</span><strong>{report.maintenance.active}</strong><p>{report.maintenance.urgent} requieren prioridad</p><Trend value={trend(report.maintenance.active,benchmark.activeTickets)} inverse/></article></section><section className="report-executive-grid"><article className="report-health"><header><div><span>Salud operativa</span><h3>Lo que requiere atención</h3></div><HiExclamationTriangle/></header><button type="button" onClick={()=>onOpenModule("utilities")}><i className={report.utilities.anomalies?"danger":"ok"}/><span><strong>{report.utilities.anomalies} consumos o servicios con incidencia</strong><small>Abrir Servicios y medidores con el contexto actual</small></span><HiArrowRight/></button><button type="button" onClick={()=>navigate("/properties/tickets")}><i className={report.maintenance.urgent?"warning":"ok"}/><span><strong>{report.maintenance.urgent} tickets urgentes o de prioridad alta</strong><small>{report.maintenance.resolved} resueltos en el periodo</small></span><HiArrowRight/></button><button type="button" onClick={()=>onOpenModule("charges")}><i className={report.finance.overdue?"danger":"ok"}/><span><strong>{money(report.finance.overdue)} en cuotas vencidas</strong><small>Consultar cargos y responsables por unidad</small></span><HiArrowRight/></button></article><article className="report-distribution"><header><span>Composición operativa</span><h3>Unidades y actividad</h3></header><div className="occupancy-bar"><i style={{width:`${report.units.occupancy}%`}}/></div><div className="report-legend"><span><i className="occupied"/>{report.units.occupied} ocupadas</span><span><i className="available"/>{report.units.available} disponibles</span><span><i className="maintenance"/>{report.units.maintenance} mantenimiento</span></div><dl><div><dt>Personas vinculadas</dt><dd>{report.community.people}</dd></div><div><dt>Lecturas de servicios</dt><dd>{report.utilities.readings}</dd></div><div><dt>Actividad en tickets</dt><dd>{report.maintenance.periodActivity}</dd></div><div><dt>Lecturas de comunicados</dt><dd>{report.community.reads}</dd></div></dl></article></section></>}

    {detail==="finance"&&<section className="report-detail-section"><header><div><span>Ingresos y ocupación</span><h3>Finanzas, rentas y hospedaje</h3></div><button type="button" onClick={()=>navigate("/properties/rentas")}>Abrir Rentas <HiArrowRight/></button></header><div className="report-finance-kpis"><article><small>Cuotas facturadas</small><strong>{money(report.finance.billed)}</strong><span>{REPORT_PERIOD_LABEL[period]}</span></article><article><small>Cuotas cobradas</small><strong>{money(report.finance.collected)}</strong><span>{report.finance.collectionRate}% de cumplimiento</span></article><article><small>Saldo vencido</small><strong>{money(report.finance.overdue)}</strong><span>Requiere seguimiento</span></article><article><small>Renta potencial mensual</small><strong>{money(rentalPotential)}</strong><span>Referencia de unidades activas</span></article></div><div className="report-two-columns"><article><header><HiBanknotes/><div><strong>Cuotas de la comunidad</strong><small>Estado por concepto y unidad</small></div></header>{charges.map(item=><div key={item.id}><span><strong>{item.concept}</strong><small>{units.find(unit=>unit.id===item.unitId)?.identifier||"Cargo general"}</small></span><b>{money(item.amount)}</b><i className={item.status}>{item.status==="paid"?"Pagado":item.status==="overdue"?"Vencido":"Pendiente"}</i></div>)}{!charges.length?<p>Sin cargos en esta comunidad.</p>:null}</article><article><header><HiCalendarDays/><div><strong>{hospitality.length?"Hospedaje":"Rendimiento de renta"}</strong><small>{hospitality.length?`${currentStays} estancias activas`:"Inventario y ocupación actual"}</small></div></header>{hospitality.length?<><div><span><strong>Reservaciones</strong><small>{hospitality.length} registros vinculados</small></span><b>{money(hospitalityRevenue)}</b><i>{money(hospitalityCollected)} recibido</i></div><div><span><strong>Saldo de hospedaje</strong><small>Importe informativo</small></span><b>{money(hospitalityRevenue-hospitalityCollected)}</b><i>Pendiente</i></div><button type="button" onClick={()=>navigate("/properties/rentas/hospedaje")}>Abrir Hospedaje <HiArrowRight/></button></>:<><div><span><strong>Ocupación de unidades</strong><small>{report.units.occupied} ocupadas</small></span><b>{report.units.occupancy}%</b><i>{report.units.available} disponibles</i></div><div><span><strong>Referencia mensual</strong><small>Suma de renta sugerida</small></span><b>{money(rentalPotential)}</b><i>No es cobranza real</i></div></>}</article></div></section>}

    {detail==="utilities"&&<section className="report-detail-section"><header><div><span>Consumo y evidencia</span><h3>Servicios básicos y medidores</h3></div><button type="button" onClick={()=>onOpenModule("utilities")}>Abrir Servicios <HiArrowRight/></button></header><div className="report-finance-kpis"><article><small>Servicios registrados</small><strong>{report.utilities.count}</strong><span>Comunes e individuales</span></article><article><small>Importe informativo</small><strong>{money(report.utilities.amount)}</strong><span>No procesado por Own Terra</span></article><article><small>Anomalías</small><strong>{report.utilities.anomalies}</strong><span>Consumo o incidencia</span></article><article><small>Evidencias pendientes</small><strong>{report.utilities.evidencePending}</strong><span>{report.utilities.verified} verificadas</span></article></div><div className="report-utilities-layout"><article><header><span>Distribución del importe</span><h4>Por tipo de servicio</h4></header>{[["Agua","water"],["Luz","electricity"],["Gas","gas"],["Internet y otros","internet"]].map(([label,key])=><div key={key}><span>{label}</span><strong>{money(serviceByType[key]||0)}</strong><i style={{width:`${report.utilities.amount?Math.round((serviceByType[key]||0)/report.utilities.amount*100):0}%`}}/></div>)}</article><article><header><span>Servicios que requieren seguimiento</span><h4>Evidencia, vencimiento y anomalías</h4></header>{services.filter(item=>item.anomaly||["incident","overdue","pending_evidence","due_soon"].includes(item.status)).map(item=><button type="button" key={item.id} onClick={()=>onOpenModule("utilities")}><span><strong>{item.name}</strong><small>{units.find(unit=>unit.id===item.unitId)?.identifier||"Servicio común"} · {item.provider}</small></span><b>{item.currentReading} {item.unit}</b><i className={item.status}>{item.anomaly?"Consumo atípico":item.status.replaceAll("_"," ")}</i><HiArrowRight/></button>)}{!services.length?<p>Sin servicios registrados.</p>:null}</article></div></section>}

    {detail==="maintenance"&&<section className="report-detail-section"><header><div><span>Atención operativa</span><h3>Tickets y mantenimiento</h3></div><button type="button" onClick={()=>navigate("/properties/tickets")}>Abrir Tickets <HiArrowRight/></button></header><div className="report-finance-kpis"><article><small>Tickets activos</small><strong>{report.maintenance.active}</strong><span>En toda la propiedad</span></article><article><small>Prioridad alta</small><strong>{report.maintenance.urgent}</strong><span>Requieren atención</span></article><article><small>Resueltos</small><strong>{report.maintenance.resolved}</strong><span>{REPORT_PERIOD_LABEL[period]}</span></article><article><small>Actividad</small><strong>{report.maintenance.periodActivity}</strong><span>Creados o actualizados</span></article></div><div className="report-ticket-list">{tickets.map(item=><button type="button" key={item.id} onClick={()=>navigate(`/properties/tickets?unitId=${item.unitId||""}`)}><span className={`ticket-dot ${item.priority}`}/><span><small>{item.folio} · {item.type}</small><strong>{item.title}</strong><em>{units.find(unit=>unit.id===item.unitId)?.identifier||property?.name} · {item.assignee||"Por asignar"}</em></span><i className={item.status}>{item.status.replaceAll("_"," ")}</i><HiArrowRight/></button>)}{!tickets.length?<p>No hay tickets relacionados.</p>:null}</div></section>}

    {detail==="community"&&<section className="report-detail-section"><header><div><span>Personas y participación</span><h3>Actividad de la comunidad</h3></div><button type="button" onClick={()=>navigate("/properties/comunidades")}>Abrir directorio <HiArrowRight/></button></header><div className="report-community-kpis"><article><HiUserGroup/><strong>{report.community.people}</strong><span>personas vinculadas</span></article><article><HiMegaphone/><strong>{report.community.announcements}</strong><span>comunicados del periodo</span></article><article><HiCheckCircle/><strong>{report.community.reads}</strong><span>lecturas registradas</span></article><article><HiCalendarDays/><strong>{report.community.amenityReservations}</strong><span>reservas de amenidades</span></article><article><HiScale/><strong>{report.community.openVotes}</strong><span>votaciones abiertas</span></article></div><div className="report-community-grid"><article><header><HiMegaphone/><span><strong>Comunicaciones</strong><small>Alcance y lectura</small></span></header>{announcements.map(item=><div key={item.id}><span><strong>{item.title}</strong><small>{item.body}</small></span><b>{item.readCount} lecturas</b></div>)}{!announcements.length?<p>Sin comunicados en este periodo.</p>:null}</article><article><header><HiScale/><span><strong>Gobernanza y amenidades</strong><small>Participación activa</small></span></header>{votes.map(item=><div key={item.id}><span><strong>{item.title}</strong><small>Cierra {item.closesAt}</small></span><b>{item.yes+item.no+item.abstain} votos</b></div>)}{reservations.map(item=><div key={item.id}><span><strong>Reserva de amenidad</strong><small>{item.personName} · {item.date} {item.time}</small></span><b>Confirmada</b></div>)}</article></div></section>}

    <footer className="report-center-footer"><HiChartBar/><p><strong>Fuente única de verdad.</strong> Este reporte lee los registros de cada módulo; no crea cifras paralelas. Selecciona cualquier bloque para regresar al origen del dato.</p><span><HiClock/> Próxima fase: reportes programados y exportación estructurada</span></footer>
  </section>;
}

export default CommunityReportsPanel;
