import { useMemo, useState } from "react";
import { HiArrowLeft, HiArrowRight, HiBanknotes, HiBuildingStorefront, HiChartBar, HiCheckCircle, HiDocumentText, HiMegaphone, HiPlus, HiQrCode, HiScale, HiWrenchScrewdriver } from "react-icons/hi2";
import { useNavigate, useSearchParams } from "react-router-dom";
import EcoLayout from "@/pages/Ecosystem/EcoLayout";
import { useAppContext } from "@/context/AppContext";
import { usePropertiesData } from "../../data/PropertiesDataContext";
import "./condo-operations.css";

const modules=[
  ["charges","Cuotas y adeudos",HiBanknotes],["communications","Comunicados",HiMegaphone],["amenities","Amenidades",HiBuildingStorefront],["committee","Comité y votaciones",HiScale],["reports","Reportes",HiChartBar],
];
const money=value=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(value||0);

function CondoOperationsSuite(){
  const navigate=useNavigate();const [params,setParams]=useSearchParams();const {showToast}=useAppContext();
  const data=usePropertiesData();
  const [communityId,setCommunityId]=useState(data.communities[0]?.id||"");
  const requested=params.get("module");const [active,setActive]=useState(modules.some(([key])=>key===requested)?requested:"charges");
  const [draft,setDraft]=useState({});
  const community=data.communities.find(item=>item.id===communityId);
  const units=data.units.filter(item=>item.propertyId===community?.propertyId&&item.status!=="archived");
  const charges=data.condoCharges.filter(item=>item.communityId===communityId);const announcements=data.announcements.filter(item=>item.communityId===communityId);const amenities=data.amenities.filter(item=>item.communityId===communityId);const reservations=data.reservations.filter(item=>item.communityId===communityId);const votes=data.votes.filter(item=>item.communityId===communityId);
  const totals=useMemo(()=>({billed:charges.reduce((sum,item)=>sum+item.amount,0),paid:charges.filter(item=>item.status==="paid").reduce((sum,item)=>sum+item.amount,0),overdue:charges.filter(item=>item.status==="overdue").reduce((sum,item)=>sum+item.amount,0)}),[charges]);
  const select=key=>{setActive(key);setDraft({});setParams({module:key},{replace:true})};
  const submit=event=>{event.preventDefault();try{
    if(active==="charges")data.addCondoCharge({...draft,communityId});
    if(active==="communications")data.addAnnouncement({...draft,communityId});
    if(active==="amenities")data.addReservation({...draft,communityId});
    if(active==="committee")data.addVote({...draft,communityId});
    setDraft({});showToast("Registro guardado para esta sesión","success");
  }catch(error){showToast(error.message,"warning")}};
  return <EcoLayout active="properties" title="Operación condominal" subtitle={`${community?.name||"Comunidad"} · Segundo nivel`}><main className="condo-suite">
    <button className="condo-back" type="button" onClick={()=>navigate("/properties/condominios")}><HiArrowLeft/> Configuración de comunidad</button>
    <header className="condo-suite-heading"><div><span>Condominios · Operación diaria</span><h1>Todo lo que mantiene viva la comunidad.</h1></div><label><small>Comunidad activa</small><select value={communityId} onChange={event=>setCommunityId(event.target.value)}>{data.communities.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></header>
    <nav className="condo-module-tabs">{modules.map(([key,label,Icon])=><button type="button" key={key} className={active===key?"active":""} onClick={()=>select(key)}><Icon/><span>{label}</span></button>)}</nav>
    <section className="condo-field-shortcuts" aria-labelledby="condo-field-title">
      <header><span>Operación en sitio</span><strong id="condo-field-title">Accesos y red de servicio</strong></header>
      <button type="button" onClick={()=>navigate("/properties/accesos")}><span><HiQrCode/></span><span><strong>Accesos y paquetería</strong><small>Visitas, pases, caseta y entregas</small></span><HiArrowRight/></button>
      <button type="button" onClick={()=>navigate("/properties/responsables")}><span><HiWrenchScrewdriver/></span><span><strong>Proveedores y responsables</strong><small>Equipo, especialidades y carga operativa</small></span><HiArrowRight/></button>
    </section>
    {active==="charges"&&<section className="condo-module"><header><div><span>Cobranza condominal</span><h2>Cuotas, cargos, pagos y adeudos</h2></div><div className="condo-kpis"><span>Facturado <b>{money(totals.billed)}</b></span><span>Cobrado <b>{money(totals.paid)}</b></span><span>Vencido <b>{money(totals.overdue)}</b></span></div></header><div className="condo-split"><form onSubmit={submit}><h3><HiPlus/> Nuevo cargo</h3><label>Concepto<input required value={draft.concept||""} onChange={e=>setDraft({...draft,concept:e.target.value})}/></label><label>Unidad<select value={draft.unitId||""} onChange={e=>setDraft({...draft,unitId:e.target.value})}><option value="">Toda la comunidad</option>{units.map(item=><option key={item.id} value={item.id}>{item.identifier}</option>)}</select></label><label>Importe<input required type="number" min="1" value={draft.amount||""} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label><label>Vencimiento<input type="date" value={draft.dueDate||""} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></label><button type="submit">Generar cargo</button></form><div className="condo-records">{charges.map(item=><article key={item.id}><span className={`condo-state ${item.status}`}>{item.status==="paid"?"Pagado":item.status==="overdue"?"Vencido":"Pendiente"}</span><div><strong>{item.concept}</strong><small>{units.find(unit=>unit.id===item.unitId)?.identifier||"Cargo general"} · vence {item.dueDate||"sin fecha"}</small></div><b>{money(item.amount)}</b>{item.status!=="paid"&&<button type="button" onClick={()=>data.markCondoChargePaid(item.id)}><HiCheckCircle/> Registrar pago</button>}</article>)}</div></div></section>}
    {active==="communications"&&<section className="condo-module"><header><div><span>Información oficial</span><h2>Comunicados y documentos</h2></div></header><div className="condo-split"><form onSubmit={submit}><h3><HiPlus/> Nuevo comunicado</h3><label>Título<input required value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Audiencia<select value={draft.audience||"all"} onChange={e=>setDraft({...draft,audience:e.target.value})}><option value="all">Toda la comunidad</option><option value="owners">Propietarios</option><option value="residents">Residentes</option></select></label><label>Mensaje<textarea required rows="5" value={draft.body||""} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><button type="submit">Publicar comunicado</button></form><div className="condo-records">{announcements.map(item=><article key={item.id}><HiDocumentText className="record-icon"/><div><strong>{item.title}</strong><small>{item.body}</small><em>{item.readCount} lecturas · {item.audience}</em></div></article>)}</div></div></section>}
    {active==="amenities"&&<section className="condo-module"><header><div><span>Espacios compartidos</span><h2>Amenidades y reservaciones</h2></div></header><div className="condo-split"><form onSubmit={submit}><h3><HiPlus/> Nueva reservación</h3><label>Amenidad<select required value={draft.amenityId||""} onChange={e=>setDraft({...draft,amenityId:e.target.value})}><option value="">Seleccionar</option>{amenities.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Persona<input required value={draft.personName||""} onChange={e=>setDraft({...draft,personName:e.target.value})}/></label><label>Fecha<input required type="date" value={draft.date||""} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Horario<input required type="time" value={draft.time||""} onChange={e=>setDraft({...draft,time:e.target.value})}/></label><button type="submit">Confirmar reservación</button></form><div className="condo-records">{reservations.map(item=><article key={item.id}><HiBuildingStorefront className="record-icon"/><div><strong>{amenities.find(a=>a.id===item.amenityId)?.name}</strong><small>{item.personName} · {item.date} a las {item.time}</small></div><span className="condo-state paid">Confirmada</span></article>)}</div></div></section>}
    {active==="committee"&&<section className="condo-module"><header><div><span>Gobernanza</span><h2>Comité, votaciones y aprobaciones</h2></div></header><div className="condo-split"><form onSubmit={submit}><h3><HiPlus/> Nueva votación</h3><label>Asunto<input required value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Descripción<textarea rows="4" value={draft.description||""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Cierre<input required type="date" value={draft.closesAt||""} onChange={e=>setDraft({...draft,closesAt:e.target.value})}/></label><button type="submit">Abrir votación</button></form><div className="condo-records">{votes.map(item=><article key={item.id}><HiScale className="record-icon"/><div><strong>{item.title}</strong><small>{item.description} · cierra {item.closesAt}</small><em>Sí {item.yes} · No {item.no} · Abstenciones {item.abstain}</em></div><button type="button" onClick={()=>data.castVote(item.id,"yes")}>Votar sí</button></article>)}</div></div></section>}
    {active==="reports"&&<section className="condo-module"><header><div><span>Lectura ejecutiva</span><h2>Reportes de la comunidad</h2></div></header><div className="condo-report-grid"><article><HiBanknotes/><span>Cobranza</span><strong>{totals.billed?Math.round(totals.paid/totals.billed*100):0}%</strong><p>de cargos cobrados</p></article><article><HiMegaphone/><span>Comunicación</span><strong>{announcements.reduce((sum,item)=>sum+item.readCount,0)}</strong><p>lecturas registradas</p></article><article><HiBuildingStorefront/><span>Amenidades</span><strong>{reservations.length}</strong><p>reservaciones activas</p></article><article><HiScale/><span>Gobernanza</span><strong>{votes.filter(item=>item.status==="open").length}</strong><p>votaciones abiertas</p></article></div></section>}
  </main></EcoLayout>;
}
export default CondoOperationsSuite;
