import { useState } from "react";
import { HiArrowLeft, HiArrowRight, HiBuildingOffice2, HiCheckCircle, HiHomeModern, HiUserGroup } from "react-icons/hi2";
import { useAppContext } from "@/context/AppContext";
import { usePropertiesData } from "../../data/PropertiesDataContext";

const initial={name:"",kind:"condominium",address:"",city:"",state:"",structure:"multiple",firstUnit:"",cuotaBase:"",billingDay:"",reglamentoUrl:""};
const regimen={condominium:"condominio",horizontal_condominium:"horizontal",private_community:"fraccionamiento",residential:"mixto"};

function CommunityOnboarding(){
  const {showToast}=useAppContext();
  const {addProperty,addCommunity,addUnit}=usePropertiesData();
  const [step,setStep]=useState(1);const [draft,setDraft]=useState(initial);const [saving,setSaving]=useState(false);const [errors,setErrors]=useState({});
  const update=(key,value)=>{setDraft(current=>({...current,[key]:value}));setErrors(current=>({...current,[key]:undefined}))};
  const validate=()=>{const next={};if(step===1){if(!draft.name.trim())next.name="Escribe el nombre de la comunidad.";if(!draft.address.trim())next.address="Escribe la dirección.";if(!draft.city.trim())next.city="Escribe la ciudad o municipio.";if(!draft.state.trim())next.state="Escribe el estado."}if(step===2&&draft.structure==="single"&&!draft.firstUnit.trim())next.firstUnit="Escribe cómo identificas la unidad.";setErrors(next);return !Object.keys(next).length};
  const next=()=>{if(validate())setStep(value=>Math.min(3,value+1))};
  const submit=async()=>{setSaving(true);try{const property=await addProperty({name:draft.name,ownerId:"",type:draft.structure==="single"?"house":"apartment_building",address:draft.address,city:draft.city,state:draft.state,description:""});await addCommunity({propertyId:property.id,inmuebleId:property.inmuebleId,name:draft.name,kind:draft.kind,regime:regimen[draft.kind],cuotaBase:draft.cuotaBase,billingDay:draft.billingDay,reglamentoUrl:draft.reglamentoUrl});if(draft.structure==="single")await addUnit({propertyId:property.id,ownerId:"",identifier:draft.firstUnit,type:"house",floor:"",area:"",bedrooms:"",bathrooms:"",suggestedRent:"",status:"available",description:""});showToast("Tu comunidad está lista para continuar","success")}catch(error){showToast(error.response?.data?.error?.message||error.message,"warning")}finally{setSaving(false)}};
  return <section className="community-onboarding">
    <header><span>Configuración inicial</span><h1>Crea tu primera comunidad</h1><p>Te guiaremos para registrar el lugar, su estructura y la configuración básica. Podrás completar personas y unidades después.</p></header>
    <ol className="community-onboarding-steps">{[[1,"Comunidad"],[2,"Estructura"],[3,"Operación"]].map(([number,label])=><li key={number} className={step===number?"active":step>number?"done":""}><i>{step>number?<HiCheckCircle/>:number}</i><span>{label}</span></li>)}</ol>
    <div className="community-onboarding-card">
      {step===1?<><div className="community-onboarding-title"><HiBuildingOffice2/><div><small>Paso 1 de 3</small><h2>¿Qué lugar administras?</h2><p>Crearemos el inmueble base y su comunidad al terminar.</p></div></div><div className="community-onboarding-grid"><label><span>Tipo</span><select value={draft.kind} onChange={event=>update("kind",event.target.value)}><option value="condominium">Condominio vertical</option><option value="horizontal_condominium">Condominio horizontal</option><option value="private_community">Fraccionamiento o privada</option><option value="residential">Comunidad mixta</option></select></label><label><span>Nombre de la comunidad</span><input autoFocus value={draft.name} onChange={event=>update("name",event.target.value)} placeholder="Ej. Condominio Jacarandas"/>{errors.name?<em>{errors.name}</em>:null}</label><label className="wide"><span>Dirección</span><input value={draft.address} onChange={event=>update("address",event.target.value)} placeholder="Calle, número y colonia"/>{errors.address?<em>{errors.address}</em>:null}</label><label><span>Ciudad o municipio</span><input value={draft.city} onChange={event=>update("city",event.target.value)}/>{errors.city?<em>{errors.city}</em>:null}</label><label><span>Estado</span><input value={draft.state} onChange={event=>update("state",event.target.value)}/>{errors.state?<em>{errors.state}</em>:null}</label></div></>:null}
      {step===2?<><div className="community-onboarding-title"><HiHomeModern/><div><small>Paso 2 de 3</small><h2>¿Cómo está organizado?</h2><p>Una comunidad puede administrar una sola unidad o muchas casas, departamentos y espacios.</p></div></div><div className="community-structure-options"><button type="button" className={draft.structure==="multiple"?"active":""} onClick={()=>update("structure","multiple")}><HiBuildingOffice2/><strong>Tiene varias unidades</strong><span>Agregaré departamentos, casas, locales o espacios después.</span></button><button type="button" className={draft.structure==="single"?"active":""} onClick={()=>update("structure","single")}><HiHomeModern/><strong>Es una sola unidad</strong><span>El inmueble completo funciona como una unidad administrada.</span></button></div>{draft.structure==="single"?<label className="community-onboarding-single"><span>Identificador de la unidad</span><input value={draft.firstUnit} onChange={event=>update("firstUnit",event.target.value)} placeholder="Ej. Casa 1, Local principal"/>{errors.firstUnit?<em>{errors.firstUnit}</em>:null}</label>:<aside><HiUserGroup/><span><strong>No necesitas capturarlas todas ahora.</strong><small>Al terminar podrás agregarlas individualmente desde la estructura de la comunidad.</small></span></aside>}</>:null}
      {step===3?<><div className="community-onboarding-title"><HiCheckCircle/><div><small>Paso 3 de 3</small><h2>Configuración operativa inicial</h2><p>Estos datos son opcionales y se pueden modificar después.</p></div></div><div className="community-onboarding-grid"><label><span>Cuota base mensual</span><input type="number" min="0" value={draft.cuotaBase} onChange={event=>update("cuotaBase",event.target.value)} placeholder="Ej. 1500"/></label><label><span>Día habitual de cobro</span><input type="number" min="1" max="28" value={draft.billingDay} onChange={event=>update("billingDay",event.target.value)} placeholder="1–28"/></label><label className="wide"><span>Enlace al reglamento</span><input type="url" value={draft.reglamentoUrl} onChange={event=>update("reglamentoUrl",event.target.value)} placeholder="https://..."/></label></div><section className="community-onboarding-summary"><strong>Al crearla, OwnTerra registrará:</strong><span><HiCheckCircle/> El inmueble raíz compartido con Core</span><span><HiCheckCircle/> La comunidad operativa</span><span><HiCheckCircle/> {draft.structure==="single"?"La primera unidad":"El espacio para agregar sus unidades"}</span></section></>:null}
      <footer>{step>1?<button type="button" className="secondary" onClick={()=>setStep(value=>value-1)}><HiArrowLeft/> Atrás</button>:<span/>}{step<3?<button type="button" onClick={next}>Continuar <HiArrowRight/></button>:<button type="button" disabled={saving} onClick={submit}>{saving?"Creando comunidad…":"Crear comunidad"} <HiArrowRight/></button>}</footer>
    </div>
  </section>;
}
export default CommunityOnboarding;
