const modules={
propiedades:{title:'Propiedades',group:'Inventario',desc:'Portafolio de inmuebles, ubicación, características, galería y estatus.',action:'Nueva propiedad',stats:['24','18','6','87%'],heads:['Propiedad','Tipo','Ubicación','Unidades','Propietario','Estado'],rows:[['Torre Jacarandas','Edificio','Benito Juárez, CDMX','12','Inversiones Roble','Activa'],['Casa Olivo','Casa','Mérida, Yucatán','1','Sofía Mendoza','Activa'],['Plaza Norte','Comercial','Monterrey, N.L.','7','Grupo Arboleda','Activa']]},
unidades:{title:'Unidades y espacios',group:'Inventario',desc:'Espacios rentables o vendibles dentro de cada propiedad.',action:'Nueva unidad',stats:['48','37','7','4'],heads:['Unidad','Propiedad','Tipo','Superficie','Precio','Estado'],rows:[['Departamento 302','Torre Jacarandas','Departamento','92 m²','$18,500 / mes','Rentada'],['Local 4','Plaza Norte','Local comercial','74 m²','$31,200 / mes','Disponible'],['Habitación 2','Casa Olivo','Habitación','18 m²','$7,800 / mes','Mantenimiento']]},
propietarios:{title:'Propietarios',group:'Inventario',desc:'Directorio de personas y empresas con sus activos administrados.',action:'Nuevo propietario',stats:['14','12','2','31'],heads:['Propietario','Tipo','Contacto','Propiedades','Unidades','Estado'],rows:[['Inversiones Roble','Empresa','contacto@roble.mx','3','18','Activo'],['Sofía Mendoza','Persona','sofia@email.mx','1','1','Activo'],['Grupo Arboleda','Empresa','admin@arboleda.mx','2','7','Invitado']]},
contratos:{title:'Contratos',group:'Administración',desc:'Altas, renovaciones, cancelaciones e historial de arrendamiento.',action:'Nuevo contrato',stats:['42','36','3','3'],heads:['Contrato','Inmueble / unidad','Inquilino','Vigencia','Renta','Estado'],rows:[['CTR-024','Torre Jacarandas · 302','Mariana Torres','01 sep 2026 – 31 ago 2027','$18,500','Vigente'],['CTR-019','Casa Olivo','Jorge Álvarez','15 ene – 14 dic 2026','$24,000','Por vencer'],['CTR-011','Plaza Norte · Local 4','Café Alba, S.A.','01 mar 2025 – 28 feb 2027','$31,200','Vigente']]},
rentas:{title:'Rentas y cobranza',group:'Administración',desc:'Calendario de cargos, seguimiento de pagos y estados de cuenta.',action:'Registrar pago',stats:['$286,400','$44,200','$3,200','93%'],heads:['Folio','Concepto','Responsable','Vencimiento','Importe','Estado'],rows:[['REN-1082','Renta agosto · Unidad 302','Mariana Torres','05 ago 2026','$18,500','Pagado'],['REN-1081','Renta agosto · Casa Olivo','Jorge Álvarez','05 ago 2026','$24,000','Pendiente'],['REN-1074','Mantenimiento · Local 4','Café Alba, S.A.','01 ago 2026','$3,200','Vencido']]},
mantenimiento:{title:'Mantenimiento',group:'Operación',desc:'Tickets, responsables, prioridades y seguimiento de incidencias.',action:'Nueva solicitud',stats:['8','3','4','1'],heads:['Ticket','Incidencia','Ubicación','Responsable','Prioridad','Estado'],rows:[['MAN-041','Fuga en lavabo principal','Torre Jacarandas · 302','Plomería Díaz','Alta','En progreso'],['MAN-038','Luminaria de pasillo','Plaza Norte','Equipo interno','Media','Abierto'],['MAN-032','Revisión de minisplit','Casa Olivo','Climas del Sur','Baja','Resuelto']]},
documentos:{title:'Documentos',group:'Expedientes',desc:'Contratos, escrituras, identificaciones, recibos y control de versiones.',action:'Subir documento',stats:['148','12','4','3'],heads:['Documento','Tipo','Relacionado con','Versión','Actualizado','Estado'],rows:[['Contrato firmado 302.pdf','Arrendamiento','CTR-024','v2','12 ago 2026','Vigente'],['Escritura Casa Olivo.pdf','Escritura','Casa Olivo','v1','04 ago 2026','Verificado'],['Recibo mantenimiento.pdf','Comprobante','REN-1074','v1','01 ago 2026','Nuevo']]},
inspecciones:{title:'Inspecciones',group:'Operación',desc:'Checklists, evidencia fotográfica, daños y firmas de entrega.',action:'Programar inspección',stats:['5','2','2','1'],heads:['Inspección','Tipo','Ubicación','Fecha','Inspector','Estado'],rows:[['INS-018','Entrada','Torre Jacarandas · 302','20 ago 2026','Ana Castillo','Programada'],['INS-016','Periódica','Casa Olivo','14 ago 2026','Diego Ruiz','Completada'],['INS-012','Mantenimiento','Plaza Norte · Local 4','02 ago 2026','Ana Castillo','Con hallazgos']]},
prospectos:{title:'Prospectos',group:'Comercial',desc:'CRM ligero para interesados y programación de visitas.',action:'Nuevo prospecto',stats:['28','7','5','18%'],heads:['Prospecto','Interés','Origen','Asesor','Último contacto','Estado'],rows:[['Andrea Molina','Torre Jacarandas · 401','Sitio web','Luis Rojas','Hoy, 10:42','Visita agendada'],['Grupo Velar','Plaza Norte · Local 2','Referido','Ana Castillo','Ayer','Negociación'],['Carlos Mejía','Casa Olivo','Marketplace','Luis Rojas','14 ago','Nuevo']]},
proveedores:{title:'Proveedores',group:'Operación',desc:'Directorio, especialidades, asignaciones y evaluación de servicio.',action:'Nuevo proveedor',stats:['24','18','5','4.7'],heads:['Proveedor','Especialidad','Contacto','Trabajos','Evaluación','Estado'],rows:[['Plomería Díaz','Plomería','55 2910 4812','18','4.9 / 5','Disponible'],['Climas del Sur','Aire acondicionado','99 9218 7701','11','4.7 / 5','Asignado'],['Segurix','Seguridad','55 9183 3200','7','4.5 / 5','Disponible']]},
publicaciones:{title:'Publicaciones',group:'Marketplace',desc:'Anuncios de renta o venta, revisión editorial y publicación.',action:'Crear publicación',stats:['12','4','63','8'],heads:['Publicación','Modalidad','Precio','Consultas','Actualizada','Estado'],rows:[['Departamento iluminado en Del Valle','Renta','$18,500 / mes','21','Hoy','Publicada'],['Local comercial con terraza','Renta comercial','$31,200 / mes','8','Ayer','En revisión'],['Casa Olivo · 3 recámaras','Venta','$5,850,000','34','12 ago','Pausada']]},
mensajes:{title:'Mensajes',group:'Comunicación',desc:'Conversaciones con propietarios, inquilinos, proveedores y prospectos.',action:'Nuevo mensaje',stats:['6','18','3','2'],heads:['Conversación','Relacionado con','Último mensaje','Hora','Asignado a','Estado'],rows:[['Mariana Torres','Contrato CTR-024','Gracias, envío el comprobante…','11:26','Ana Castillo','Sin leer'],['Plomería Díaz','Ticket MAN-041','Llegamos mañana a las 9:00','10:04','Diego Ruiz','Respondido'],['Andrea Molina','Prospecto','¿Podemos visitar el sábado?','Ayer','Luis Rojas','Pendiente']]},
notificaciones:{title:'Notificaciones',group:'Seguimiento',desc:'Alertas de rentas, contratos, mantenimiento y actividad comercial.',action:'Configurar alertas',stats:['9','4','3','2'],heads:['Alerta','Categoría','Relacionado con','Fecha','Destinatario','Estado'],rows:[['Contrato próximo a vencer','Contratos','CTR-019','Hoy','Ana Castillo','Pendiente'],['Renta vencida','Cobranza','REN-1074','Ayer','Café Alba, S.A.','Enviada'],['Nueva consulta de publicación','Prospectos','Casa Olivo','14 ago','Luis Rojas','Leída']]},
actividad:{title:'Actividad',group:'Auditoría',desc:'Línea de tiempo unificada de cambios y eventos del portafolio.',action:'Exportar actividad',stats:['17','84','6','3'],heads:['Evento','Módulo','Registro','Realizado por','Fecha','Resultado'],rows:[['Pago registrado','Cobranza','REN-1082','Ana Castillo','Hoy, 11:18','Completado'],['Estatus actualizado','Mantenimiento','MAN-041','Diego Ruiz','Hoy, 09:32','En progreso'],['Documento cargado','Documentos','CTR-024','Ana Castillo','Ayer, 16:45','Completado']]},
'portal-inquilino':{title:'Portal del inquilino',group:'Portal',desc:'Contrato, próximos pagos, solicitudes, documentos y mensajes.',action:'Vista previa',stats:['38','31','5','2'],heads:['Inquilino','Unidad','Próximo pago','Solicitudes','Documentos','Acceso'],rows:[['Mariana Torres','Torre Jacarandas · 302','$18,500 · 05 sep','1 abierta','8','Activo'],['Jorge Álvarez','Casa Olivo','$24,000 · 05 sep','Sin solicitudes','6','Invitado'],['Café Alba, S.A.','Plaza Norte · Local 4','$34,400 · 01 sep','1 resuelta','11','Activo']]},
'portal-propietario':{title:'Portal del propietario',group:'Portal',desc:'Rendimiento, ocupación, contratos, reportes y documentos.',action:'Vista previa',stats:['14','12','2','87%'],heads:['Propietario','Portafolio','Ocupación','Ingreso mensual','Reporte','Acceso'],rows:[['Inversiones Roble','3 propiedades · 18 unidades','89%','$264,700','Agosto listo','Activo'],['Sofía Mendoza','1 propiedad · 1 unidad','100%','$24,000','Agosto listo','Activo'],['Grupo Arboleda','2 propiedades · 7 unidades','71%','$118,900','En preparación','Invitado']]}}
const files=['propiedades','unidades','propietarios','contratos','rentas','mantenimiento','documentos','inspecciones','prospectos','proveedores','publicaciones','mensajes','notificaciones','actividad','portal-inquilino','portal-propietario'];
const icon=(n)=>['⌂','▦','○','▤','＄','⌁','□','✓','◇','⚒','◉','✉','●','↻','♙','♜'][files.indexOf(n)]||'◇';
function shell(main,active='inicio'){return `<div class="app"><aside class="sidebar"><div class="brand"><div class="mark">OT</div><div>Own Terra<small>Properties</small></div></div><div class="nav"><div class="nav-label">General</div><a class="${active==='inicio'?'active':''}" href="index.html"><i class="dot"></i><span>Panel general</span></a><div class="nav-label">Inventario</div>${files.slice(0,3).map(n=>`<a class="${active===n?'active':''}" href="${n}.html"><i class="dot"></i><span>${modules[n].title}</span></a>`).join('')}<div class="nav-label">Administración</div>${files.slice(3,10).map(n=>`<a class="${active===n?'active':''}" href="${n}.html"><i class="dot"></i><span>${modules[n].title}</span></a>`).join('')}<div class="nav-label">Experiencias</div>${files.slice(10).map(n=>`<a class="${active===n?'active':''}" href="${n}.html"><i class="dot"></i><span>${modules[n].title}</span></a>`).join('')}</div></aside><section class="workspace"><header class="topbar"><div><h2>Own Terra Properties</h2><p>Grupo Terranova · Espacio de administración</p></div><div class="avatar">FE</div></header><main class="content">${main}</main></section></div>`}
function renderIndex(){const cards=files.map(n=>`<a class="module" href="${n}.html"><span class="module-icon">${icon(n)}</span><div><small>${modules[n].group}</small><h3>${modules[n].title}</h3><p>${modules[n].desc}</p></div><footer><span>Abrir vista</span><b>→</b></footer></a>`).join('');return shell(`<section class="hero"><div><span class="hero-label">Referencia visual · MVP</span><h1>La operación inmobiliaria, en un solo lugar.</h1><p>Inventario, administración, comercialización y portales conectados por una experiencia clara. Estas vistas son únicamente plantillas HTML de referencia.</p></div></section><div class="notice">Prototipo visual estático: los botones y registros no están conectados a servicios ni guardan información.</div><section class="module-grid">${cards}</section>`)}
function renderModule(key){const m=modules[key];if(!m)return renderIndex();const stats=m.stats.map((v,i)=>`<article class="stat"><span>${['Total','Activos','Pendientes','Indicador'][i]}</span><strong>${v}</strong><small>Datos de demostración</small></article>`).join('');const rows=m.rows.map(r=>`<tr>${r.map((c,i)=>`<td>${i===r.length-1?`<span class="badge">${c}</span>`:c}</td>`).join('')}</tr>`).join('');return shell(`<a class="back" href="index.html">← Volver al panel</a><section class="hero"><div><span class="hero-label">${m.group}</span><h1>${m.title}</h1><p>${m.desc}</p></div><button class="primary">＋ ${m.action}</button></section><div class="notice">Plantilla HTML de referencia visual. Contenido ficticio, sin conexión a backend.</div><section class="stats">${stats}</section><section class="panel"><div class="toolbar"><div class="search">⌕ Buscar en ${m.title.toLowerCase()}…</div><button class="filter">Todos los estados⌄</button></div><table><thead><tr>${m.heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></section>`,key)}
document.body.innerHTML=document.body.dataset.view==='index'?renderIndex():renderModule(document.body.dataset.view);
