export const demoRentalListings = [
  {
    id: "listing-olivo",
    slug: "casa-olivo-valle-de-bravo",
    unitId: "unit-olivo",
    title: "Casa familiar con jardín en Valle de Bravo",
    summary: "Casa completa de cuatro recámaras, jardín privado y terraza cubierta.",
    description: "Una casa independiente para renta de larga estancia, con espacios amplios, jardín privado, chimenea, estudio y terraza cubierta. Se encuentra dentro de una zona residencial arbolada con acceso controlado.",
    monthlyRent: 39000,
    deposit: 39000,
    availableFrom: "2026-09-25",
    minimumTerm: 12,
    furnished: true,
    petPolicy: "Se aceptan mascotas",
    parkingSpaces: 2,
    amenities: ["Jardín privado", "Terraza cubierta", "Chimenea", "Estudio", "Acceso controlado"],
    photoPosition: "top-left",
    photoUrl: "/properties/rental-house-valle-v1.webp",
    featured: true,
    status: "published",
    inquiries: 7,
    publishedAt: "2026-09-01T12:00:00Z",
  },
  {
    id: "listing-j401",
    slug: "departamento-jacarandas-401",
    unitId: "unit-j401",
    title: "Departamento luminoso con balcón arbolado",
    summary: "Dos recámaras, dos baños y entrega inmediata en Torre Jacarandas.",
    description: "Un hogar sereno y bien conectado, con espacios iluminados, balcón interior y un cajón de estacionamiento. La renta incluye el mantenimiento del edificio.",
    monthlyRent: 20500,
    deposit: 20500,
    availableFrom: "2026-09-15",
    minimumTerm: 12,
    furnished: false,
    petPolicy: "A consideración",
    parkingSpaces: 1,
    amenities: ["Elevador", "Roof garden", "Acceso controlado", "Balcón"],
    photoPosition: "top-left",
    featured: true,
    status: "published",
    inquiries: 12,
    publishedAt: "2026-08-24T12:00:00Z",
  },
  {
    id: "listing-a3",
    slug: "departamento-arboleda-b301",
    unitId: "unit-a3",
    title: "Departamento familiar con vista al parque",
    summary: "Unidad esquina de tres recámaras en Residencial La Arboleda.",
    description: "Distribución amplia para vida familiar, iluminación en dos fachadas y áreas verdes dentro del residencial. Cercano a servicios, escuelas y vialidades principales.",
    monthlyRent: 23900,
    deposit: 23900,
    availableFrom: "2026-10-01",
    minimumTerm: 12,
    furnished: false,
    petPolicy: "Se aceptan mascotas",
    parkingSpaces: 2,
    amenities: ["Áreas verdes", "Vigilancia", "Balcón", "Dos estacionamientos"],
    photoPosition: "top-right",
    featured: true,
    status: "published",
    inquiries: 19,
    publishedAt: "2026-08-20T12:00:00Z",
  },
  {
    id: "listing-p2",
    slug: "local-plaza-norte-2",
    unitId: "unit-p2",
    title: "Local comercial listo para adaptar",
    summary: "44 m² a nivel de calle, estacionamiento frontal y energía trifásica.",
    description: "Espacio flexible para servicios, estudio o comercio de cercanía. Cuenta con excelente exposición desde el acceso principal de Plaza Norte.",
    monthlyRent: 13200,
    deposit: 26400,
    availableFrom: "2026-09-10",
    minimumTerm: 12,
    furnished: false,
    petPolicy: "No aplica",
    parkingSpaces: 2,
    amenities: ["Nivel de calle", "Energía trifásica", "Estacionamiento", "Baño privado"],
    photoPosition: "bottom-left",
    featured: false,
    status: "published",
    inquiries: 8,
    publishedAt: "2026-08-29T12:00:00Z",
  },
  {
    id: "listing-niebla",
    slug: "cabana-niebla-tapalpa",
    unitId: "unit-niebla",
    title: "Cabaña entre pinos con chimenea",
    summary: "Dos recámaras, tapanco y terraza privada en el bosque de Tapalpa.",
    description: "Una estancia tranquila para vivir temporadas largas, rodeada de bosque y con acceso a las áreas comunes de Refugio Bosque Alto.",
    monthlyRent: 17200,
    deposit: 17200,
    availableFrom: "2026-09-20",
    minimumTerm: 6,
    furnished: true,
    petPolicy: "Se aceptan mascotas",
    parkingSpaces: 1,
    amenities: ["Amueblada", "Chimenea", "Terraza", "Vista al bosque"],
    photoPosition: "bottom-right",
    featured: true,
    status: "published",
    inquiries: 15,
    publishedAt: "2026-08-26T12:00:00Z",
  },
  {
    id: "listing-o3",
    slug: "oficina-centro-3c",
    unitId: "unit-o3",
    title: "Oficina privada en edificio histórico",
    summary: "28 m² con vista a patio central en el Centro Histórico.",
    description: "Oficina compacta para equipo pequeño, dentro de un inmueble rehabilitado y con ubicación caminable.",
    monthlyRent: 8200,
    deposit: 8200,
    availableFrom: "2026-10-01",
    minimumTerm: 6,
    furnished: false,
    petPolicy: "No aplica",
    parkingSpaces: 0,
    amenities: ["Acceso controlado", "Patio central", "Internet disponible"],
    photoPosition: "bottom-left",
    featured: false,
    status: "draft",
    inquiries: 0,
    publishedAt: "",
  },
];
